build:
  environment:
    php:
      version: 7.4
      pecl_extensions:
        - redis
  nodes:
    build:
      services:
        mariadb: 10
        redis: 6
      project_setup:
        override:
          - 'true'
      tests:
        before:
          - bin/console doctrine:database:create -n
          - bin/console doctrine:migrations:migrate -n
        override:
          -
            command: bin/phpunit
            coverage:
              file: clover.xml
              format: clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run
filter:
  excluded_paths:
    - 'tests/*'
    - 'bin/*'
checks:
  php: true
coding_style:
  php: {  }
