parameters:
    env(STORAGE_ADAPTER): 'doctrine'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/**/{DependencyInjection,Entity,Migrations,Model,Tests,Kernel.php}'

    App\Interfaces\Http\:
        resource: '../src/Interfaces/Http'
        tags: ['controller.service_arguments']

    App\Infrastructure\ObjectStorage\RedisObjectStorageAdapter:
        bind:
            $redis: '@snc_redis.object_store'
        tags: [{ name: 'object_storage.adapter', key: 'redis' }]

    App\Infrastructure\ObjectStorage\DoctrineObjectStorageAdapter:
        tags: [{ name: 'object_storage.adapter', key: 'doctrine' }]

    App\Infrastructure\ObjectStorage\AdapterProvider:
        arguments: [!tagged { tag: 'object_storage.adapter', index_by: key }, '%env(STORAGE_ADAPTER)%']

    App\Infrastructure\ObjectStorage\ObjectStorageAdapter:
        factory: '@App\Infrastructure\ObjectStorage\AdapterProvider'
