name: Tests
on: [push, pull_request]
env:
  APP_ENV: test
  DATABASE_URL: 'mysql://root@127.0.0.1/object_store?serverVersion=mariadb-10.4.11'
jobs:
  build:
    name: API CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          mysql database: object_store
      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, xml, hash, ctype, iconv, curl, pcov, pdo_mysql, redis
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: composer install -n
      - name: Prepare database
        run: |
          bin/console doctrine:migrations:migrate -n
      - name: Run Tests
        run: bin/phpunit
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: clover.xml
      - name: Run mutation tests
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        run: vendor/bin/infection --ignore-msi-with-no-mutations --min-covered-msi=50 --min-msi=50 -s -j4
      - name: Auto-merge Dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v1
        if: ${{ github.event_name == 'pull_request' }}
